version: '3'
services:
  service-discovery:
    image: eurekaserver
    container_name: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  api-gateway:
    image: apigateway
    container_name: api-gateway
    build:
      context: ../apigateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - service-discovery
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  Task1:
    image: task1
    container_name: Task1
    build:
      context: ../Task1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka/
