spring.application.name=client-app
server.port=6060
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/revshopp2
spring.datasource.username =root
spring.datasource.password=Kundu123@123
=======
spring.datasource.url=jdbc:mysql://localhost:3306/
spring.datasource.username =
spring.datasource.password=
>>>>>>> 9fe7153c58ed5587d1e2ee57638d488475e13c45
spring.jpa.hibernate.ddl-auto=update
# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379

# Session store configuration
spring.session.store-type=redis
